# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: CmdLine@2
  inputs:
    script: |
      wget https://downloads.whitesourcesoftware.com/wss-unified-agent.jar
      wget https://unified-agent.s3.amazonaws.com/wss-unified-agent.config
      java -jar wss-unified-agent.jar -c wss-unified-agent.config -d src -apiKey 8bc6944f49b24094b4e22f9b54f7d14252ca186204e9480d9f940c79282a8d9c -projectToken bc0126051b084f8c93ee7529beb1fea9a697c12ff7eb4a0aa43a6efb1ceacb7a
